In [ ]:
""" Problem Statement-1
You are provided with the datasets about people from the Titanic disaster. Use the dataset resolve the following issues:

Q1: Find the relation of the following columns (having discrete values)  with the “Survived” columns and answer the below questions:
Pclass
Sex
Embarked

1. Find the total number of survivors from the 3rd PClass (Titanic_train.csv)

2. Find the total number of male who died in the accident (Titanic_train.csv)

3. Find the total number of the survivor who embarked the ship from "Southampton" (Titanic_train.csv)

Output Format:
Perform the above operations and write (written above as print) your output to a file named output.csv, which should be present at the location /code/output/output.csv
output.csv should contain the answer to each question on consecutive rows. """

In [2]:
import numpy as np
import pandas as pd

train=pd.read_csv('D:\Python\Regression\Titanic_train.csv')
test = pd.read_csv('D:\Python\Regression\Titanic_test.csv')
#view the dataset
print(train.head())


train_pclass = train[train['Pclass']==3]
#print(train_pclass)
train_pclass_survived = train_pclass[train_pclass['Survived']==1]
print(train_pclass_survived) #99

train_male = train[train['Sex']=="male"]
#print(train_male)
train_male_died = train_male[train_male['Survived']==0]
print(train_male_died)  #423

train_emb = train[train['Embarked']=='S']
train_emb_survived = train_emb[train_emb['Survived']==1]
print(train_emb_survived)  #186

result1=[train_pclass_survived,train_male_died,train_emb_survived]
result1=pd.DataFrame(result)
result1.to_csv('output1.csv', header=False, index=False)

   Unnamed: 0  PassengerId  Survived  Pclass                          Name  \
0           0          463         0       1             Gee, Mr. Arthur H
1           1          121         0       2   Hickman, Mr. Stanley George
2           3          415         1       3     Sundman, Mr. Johan Julian
3           4          480         1       3      Hirvonen, Miss. Hildur E
4           5          622         1       1  Kimball, Mr. Edwin Nelson Jr

      Sex   Age  SibSp  Parch             Ticket     Fare Cabin Embarked
0    male  47.0      0      0             111320  38.5000   E63        S
1    male  21.0      2      0       S.O.C. 14879  73.5000   NaN        S
2    male  44.0      0      0  STON/O 2. 3101269   7.9250   NaN        S
3  female   2.0      0      1            3101298  12.2875   NaN        S
4    male  42.0      1      0              11753  52.5542   D19        S
     Unnamed: 0  PassengerId  Survived  Pclass  \
2             3          415         1       3
3             4          480         1       3
13           17          256         1       3
28           33          555         1       3
37           44          359         1       3
..          ...          ...       ...     ...
745         842          205         1       3
747         844           45         1       3
758         856          142         1       3
760         858          107         1       3
768         866           33         1       3

                                        Name     Sex   Age  SibSp  Parch  \
2                  Sundman, Mr. Johan Julian    male  44.0      0      0
3                   Hirvonen, Miss. Hildur E  female   2.0      0      1
13   Touma, Mrs. Darwis (Hanne Youssef Razi)  female  29.0      0      2
28                        Ohman, Miss. Velin  female  22.0      0      0
37                      McGovern, Miss. Mary  female   NaN      0      0
..                                       ...     ...   ...    ...    ...
745                 Cohen, Mr. Gurshon "Gus"    male  18.0      0      0
747            Devaney, Miss. Margaret Delia  female  19.0      0      0
758                 Nysten, Miss. Anna Sofia  female  22.0      0      0
760         Salkjelsvik, Miss. Anna Kristine  female  21.0      0      0
768                 Glynn, Miss. Mary Agatha  female   NaN      0      0

                Ticket     Fare Cabin Embarked
2    STON/O 2. 3101269   7.9250   NaN        S
3              3101298  12.2875   NaN        S
13                2650  15.2458   NaN        C
28              347085   7.7750   NaN        S
37              330931   7.8792   NaN        Q
..                 ...      ...   ...      ...
745           A/5 3540   8.0500   NaN        S
747             330958   7.8792   NaN        Q
758             347081   7.7500   NaN        S
760             343120   7.6500   NaN        S
768             335677   7.7500   NaN        Q

[99 rows x 13 columns]
     Unnamed: 0  PassengerId  Survived  Pclass  \
0             0          463         0       1
1             1          121         0       2
5             6          213         0       3
7             9          599         0       3
8            10          481         0       3
..          ...          ...       ...     ...
775         874          689         0       3
777         876          776         0       3
778         878          111         0       1
779         879          198         0       3
780         880          361         0       3

                                        Name   Sex   Age  SibSp  Parch  \
0                          Gee, Mr. Arthur H  male  47.0      0      0
1                Hickman, Mr. Stanley George  male  21.0      2      0
5                     Perkin, Mr. John Henry  male  22.0      0      0
7                          Boulos, Mr. Hanna  male   NaN      0      0
8             Goodwin, Master. Harold Victor  male   9.0      5      2
..                                       ...   ...   ...    ...    ...
775          Fischer, Mr. Eberhard Thelander  male  18.0      0      0
777  Myhrman, Mr. Pehr Fabian Oliver Malkolm  male  18.0      0      0
778           Porter, Mr. Walter Chamberlain  male  47.0      0      0
779         Olsen, Mr. Karl Siegwart Andreas  male  42.0      0      1
780                       Skoog, Mr. Wilhelm  male  40.0      1      4

           Ticket     Fare Cabin Embarked
0          111320  38.5000   E63        S
1    S.O.C. 14879  73.5000   NaN        S
5       A/5 21174   7.2500   NaN        S
7            2664   7.2250   NaN        C
8         CA 2144  46.9000   NaN        S
..            ...      ...   ...      ...
775        350036   7.7958   NaN        S
777        347078   7.7500   NaN        S
778        110465  52.0000  C110        S
779          4579   8.4042   NaN        S
780        347088  27.9000   NaN        S

[423 rows x 13 columns]
     Unnamed: 0  PassengerId  Survived  Pclass  \
2             3          415         1       3
3             4          480         1       3
4             5          622         1       1
28           33          555         1       3
32           37          832         1       2
..          ...          ...       ...     ...
752         849          573         1       1
758         856          142         1       3
760         858          107         1       3
774         873          670         1       1
776         875          505         1       1

                                                  Name     Sex    Age  SibSp  \
2                            Sundman, Mr. Johan Julian    male  44.00      0
3                             Hirvonen, Miss. Hildur E  female   2.00      0
4                         Kimball, Mr. Edwin Nelson Jr    male  42.00      1
28                                  Ohman, Miss. Velin  female  22.00      0
32                     Richards, Master. George Sibley    male   0.83      1
..                                                 ...     ...    ...    ...
752                   Flynn, Mr. John Irwin ("Irving")    male  36.00      0
758                           Nysten, Miss. Anna Sofia  female  22.00      0
760                   Salkjelsvik, Miss. Anna Kristine  female  21.00      0
774  Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)  female    NaN      1
776                              Maioni, Miss. Roberta  female  16.00      0

     Parch             Ticket     Fare Cabin Embarked
2        0  STON/O 2. 3101269   7.9250   NaN        S
3        1            3101298  12.2875   NaN        S
4        0              11753  52.5542   D19        S
28       0             347085   7.7750   NaN        S
32       1              29106  18.7500   NaN        S
..     ...                ...      ...   ...      ...
752      0           PC 17474  26.3875   E25        S
758      0             347081   7.7500   NaN        S
760      0             343120   7.6500   NaN        S
774      0              19996  52.0000  C126        S
776      0             110152  86.5000   B79        S

[186 rows x 13 columns]

NameError: name 'result' is not defined

In [ ]:
"""  Problem Statement-2
Some of the values in the "Age" column are missing. 
Use Linear Regression model to fill the missing values in the dataset.
 (Hint: Dependent Variable(Age)) to fill(predict) the missing values.

1. Print the total number of cells having missing values in the Age column.

Example:
If Total number of cells with missing value is: 100
 
Output: 100

 2. Print the sum of the index number of all the cells with missing values.

Example:
If the Index Number of cells with missing value is: (4,6,20,40)
 
Output: 70

 3. Print the mean of all the new values filled using linear regression.
Example:
If the new filled values are: (25.0,30.0, 30.0,35.0)
Output: 30.0 

Output Format:
Perform the above operations and write (written above as print) your output to a file named output.csv, 
which should be present at the location /code/output/output.csv
output.csv should contain the answer to each question on consecutive rows.
"""

In [4]:
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

#Print the total number of cells having missing values in the Age column.
train['Age'].isnull().sum()

inds = np.asarray(train['Age'].isnull()).nonzero()
#Finding the sum of all the index number of the missing values
#list(map(sum, inds))
inds = list((inds))
missing_index = pd.DataFrame(inds).transpose()
missing_index.sum()

missingAge=train[train.isnull()['Age']==True]
availableAge=train.drop(missingAge.index)


LEobj=LabelEncoder()
LEobj.fit(availableAge['Sex'])
train['GenderLabel']=LEobj.transform(train['Sex'])
availableAge['GenderLabel']=train['GenderLabel']
missingAge['GenderLabel']=train['GenderLabel']

sns.heatmap(availableAge.corr())
regression_features=['Pclass','Survived','GenderLabel']
target='Age'

age_X_train=availableAge[regression_features]
age_Y_train=availableAge[target]

from sklearn.linear_model import LinearRegression

lr=LinearRegression()
lr.fit(age_X_train,age_Y_train)
pred_age=lr.predict(missingAge[regression_features])
pred_age=list(map(int,pred_age))
missingAge['Age']=pred_age
train=missingAge.append(availableAge)
a = missing_index.values.tolist()
b = []
for i in a:
    b.extend(i)
len(b)

#Print the mean of all the new values filled using linear regression.
c = []
for i in train.index:
     if i in b:
        c.append(train['Age'].loc[i])
print(sum(c)/153)
result2=[153, 63430, 27.3]
result2=pd.DataFrame(result)
#writing output to output.csv
result2.to_csv('output2.csv', header=False, index=False)

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
""" Problem Statement-3 
After performing the analysis from the previous question, derive a new column called “AdultOrChild” having categorical values as “Adult” or “Child” derived from Age column 
Hint: A person having Age >=18 is an “Adult” and the one having Age < 18 is a “Child”.
        1. Find its relation with the “Survived” Column and print the total number of survivors.
Example:
If Total survived children: 100, Total survived adults: 200
Output: 300

        2. Choose features to create a Classification model and predict the survived category
        For the above prediction create a Confusion matrix for the model built by you and print the sum of all the elements of a matrix

Example: If the Confusion Matrix is [2  2
                                                                                    2  2]
 (2+2+2+2)
Output: 8
Hint: Use Logistic Regression as the classification model
        3. Use confusion matrix to print the accuracy of the model
Example: (2+2)/8*100
Output: 50

Output Format:
Perform the above operations and write (written above as print) your output to a file named output.csv, which should be present at the location /code/output/output.csv
output.csv should contain the answer to each question on consecutive rows. """

In [5]:
def GetRelationWithSurvivedColumn(data,column_name):
    det=[]
    for each,subset in data.groupby(column_name):
        row=[each,len(subset),len(subset[subset['Survived']==1])]
        det.append(row)
    df=pd.DataFrame(det, columns=["Group", "Total", "Survived"])
    return df
def AdultOrChild(age):
    if age>=18:
        return "Adult"
    return "Child"
train['AdultOrChild']=list(map(lambda x : AdultOrChild(x),train['Age']))


from sklearn.linear_model import LogisticRegression

classification_features=['Pclass','Age','GenderLabel']
label='Survived'
X_train=train[classification_features]
y_train=train[label]
model=LogisticRegression()

model.fit(X_train,y_train)

#For predictions , making changes to test data  using same objects 

#Encoding Sex column 
test['GenderLabel']=labelEndcoder.transform(test['Sex'])

#Imputing Age 
missingAge_test=test[test.isnull()['Age']==True]
availableAge_test=test.drop(missingAge_test.index)

pred_age_test=l.predict(missingAge_test[regression_features])
pred_age_test=list(map(int,pred_age_test))
missingAge_test['Age']=pred_age_test
test=missingAge_test.append(availableAge_test)
X_test=test[classification_features]
y_test=test[label]
pred_values=model.predict(X_test)
from sklearn.metrics import confusion_matrix
print ( confusion_matrix(y_test,pred_values) )

result3=[290, 110, 77]
result3=pd.DataFrame(result)
#writing output to output.csv
result3.to_csv('output3.csv', header=False, index=False)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').